CREATE TABLE shared.user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    profile_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_account_email UNIQUE (email),
    CONSTRAINT ck_user_account_role CHECK (role IN ('ADMIN', 'MANAGER', 'CONSULTANT')),
    CONSTRAINT fk_user_account_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id),
    CONSTRAINT uk_user_account_profile UNIQUE (profile_id)
);

CREATE INDEX idx_user_account_profile_id ON shared.user_account (profile_id);
