CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS crm;
CREATE SCHEMA IF NOT EXISTS staffing;
CREATE SCHEMA IF NOT EXISTS projects;
CREATE SCHEMA IF NOT EXISTS timesheets;
CREATE SCHEMA IF NOT EXISTS expenses;
CREATE SCHEMA IF NOT EXISTS absences;
CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE crm.company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name VARCHAR(150) NOT NULL,
    display_name VARCHAR(150),
    registration_number VARCHAR(50),
    vat_number VARCHAR(50),
    website_url VARCHAR(255),
    email_address VARCHAR(150),
    phone_number VARCHAR(50),
    billing_address VARCHAR(255),
    city_name VARCHAR(100),
    postal_code VARCHAR(20),
    country_code VARCHAR(2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE crm.contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(150),
    email_address VARCHAR(150),
    phone_number VARCHAR(50),
    primary_contact BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_contact_company FOREIGN KEY (company_id) REFERENCES crm.company (id)
);

CREATE TABLE staffing.profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_type VARCHAR(20) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email_address VARCHAR(150) NOT NULL,
    phone_number VARCHAR(50),
    job_title VARCHAR(150),
    seniority_label VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    default_daily_rate NUMERIC(12, 2),
    availability_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE staffing.skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_code VARCHAR(50) NOT NULL,
    skill_name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_skill_skill_code UNIQUE (skill_code)
);

CREATE TABLE staffing.need (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    contact_id BIGINT,
    need_reference VARCHAR(50),
    title VARCHAR(150) NOT NULL,
    description VARCHAR(4000),
    need_status VARCHAR(20) NOT NULL,
    start_date DATE,
    end_date DATE,
    location_name VARCHAR(150),
    remote_possible BOOLEAN NOT NULL DEFAULT FALSE,
    target_daily_rate NUMERIC(12, 2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_need_company FOREIGN KEY (company_id) REFERENCES crm.company (id),
    CONSTRAINT fk_need_contact FOREIGN KEY (contact_id) REFERENCES crm.contact (id)
);

CREATE TABLE staffing.profile_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    proficiency_level INTEGER,
    years_of_experience INTEGER,
    primary_skill BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_profile_skill_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id),
    CONSTRAINT fk_profile_skill_skill FOREIGN KEY (skill_id) REFERENCES staffing.skill (id),
    CONSTRAINT uk_profile_skill_profile_skill UNIQUE (profile_id, skill_id)
);

CREATE TABLE staffing.need_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    need_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    required_level INTEGER,
    mandatory BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_need_skill_need FOREIGN KEY (need_id) REFERENCES staffing.need (id),
    CONSTRAINT fk_need_skill_skill FOREIGN KEY (skill_id) REFERENCES staffing.skill (id),
    CONSTRAINT uk_need_skill_need_skill UNIQUE (need_id, skill_id)
);

CREATE TABLE staffing.submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    need_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    submission_status VARCHAR(20) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE,
    proposed_daily_rate NUMERIC(12, 2),
    notes VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_submission_need FOREIGN KEY (need_id) REFERENCES staffing.need (id),
    CONSTRAINT fk_submission_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id),
    CONSTRAINT uk_submission_need_profile UNIQUE (need_id, profile_id)
);

CREATE TABLE projects.project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    origin_need_id BIGINT,
    contact_id BIGINT,
    project_code VARCHAR(50) NOT NULL,
    project_name VARCHAR(150) NOT NULL,
    description VARCHAR(4000),
    project_status VARCHAR(20) NOT NULL,
    start_date DATE,
    end_date DATE,
    budget_amount NUMERIC(14, 2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_company FOREIGN KEY (company_id) REFERENCES crm.company (id),
    CONSTRAINT fk_project_origin_need FOREIGN KEY (origin_need_id) REFERENCES staffing.need (id),
    CONSTRAINT fk_project_contact FOREIGN KEY (contact_id) REFERENCES crm.contact (id),
    CONSTRAINT uk_project_origin_need UNIQUE (origin_need_id),
    CONSTRAINT uk_project_project_code UNIQUE (project_code)
);

CREATE TABLE projects.mission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    role_name VARCHAR(150) NOT NULL,
    start_date DATE,
    end_date DATE,
    daily_rate NUMERIC(12, 2),
    allocation_percent INTEGER,
    mission_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_mission_project FOREIGN KEY (project_id) REFERENCES projects.project (id),
    CONSTRAINT fk_mission_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id)
);

CREATE TABLE timesheets.time_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    mission_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    quantity NUMERIC(6, 2) NOT NULL,
    unit_type VARCHAR(20) NOT NULL,
    comment VARCHAR(1000),
    time_entry_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_time_entry_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id),
    CONSTRAINT fk_time_entry_mission FOREIGN KEY (mission_id) REFERENCES projects.mission (id)
);

CREATE TABLE expenses.expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    mission_id BIGINT NOT NULL,
    expense_date DATE NOT NULL,
    expense_category VARCHAR(30) NOT NULL,
    comment VARCHAR(1000),
    amount NUMERIC(12, 2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    receipt_url VARCHAR(500),
    billable BOOLEAN NOT NULL DEFAULT FALSE,
    expense_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_expense_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id),
    CONSTRAINT fk_expense_mission FOREIGN KEY (mission_id) REFERENCES projects.mission (id)
);

CREATE TABLE absences.absence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    absence_type VARCHAR(20) NOT NULL,
    absence_status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    quantity NUMERIC(6, 2) NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_absence_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile (id)
);

CREATE TABLE billing.invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    invoice_number VARCHAR(50) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE,
    invoice_status VARCHAR(20) NOT NULL,
    total_ht NUMERIC(14, 2) NOT NULL,
    total_vat NUMERIC(14, 2) NOT NULL,
    total_ttc NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invoice_project FOREIGN KEY (project_id) REFERENCES projects.project (id),
    CONSTRAINT uk_invoice_invoice_number UNIQUE (invoice_number)
);

CREATE TABLE billing.invoice_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    line_type VARCHAR(20) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    unit_price NUMERIC(14, 2) NOT NULL,
    tax_rate NUMERIC(5, 2),
    total_ht NUMERIC(14, 2) NOT NULL,
    total_vat NUMERIC(14, 2) NOT NULL,
    total_ttc NUMERIC(14, 2) NOT NULL,
    source_type VARCHAR(20),
    source_id BIGINT,
    display_order INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invoice_line_invoice FOREIGN KEY (invoice_id) REFERENCES billing.invoice (id)
);

CREATE INDEX idx_contact_company_id ON crm.contact (company_id);
CREATE INDEX idx_need_company_id ON staffing.need (company_id);
CREATE INDEX idx_need_contact_id ON staffing.need (contact_id);
CREATE INDEX idx_profile_skill_profile_id ON staffing.profile_skill (profile_id);
CREATE INDEX idx_profile_skill_skill_id ON staffing.profile_skill (skill_id);
CREATE INDEX idx_need_skill_need_id ON staffing.need_skill (need_id);
CREATE INDEX idx_need_skill_skill_id ON staffing.need_skill (skill_id);
CREATE INDEX idx_submission_need_id ON staffing.submission (need_id);
CREATE INDEX idx_submission_profile_id ON staffing.submission (profile_id);
CREATE INDEX idx_project_company_id ON projects.project (company_id);
CREATE INDEX idx_project_contact_id ON projects.project (contact_id);
CREATE INDEX idx_mission_project_id ON projects.mission (project_id);
CREATE INDEX idx_mission_profile_id ON projects.mission (profile_id);
CREATE INDEX idx_time_entry_profile_id ON timesheets.time_entry (profile_id);
CREATE INDEX idx_time_entry_mission_id ON timesheets.time_entry (mission_id);
CREATE INDEX idx_expense_profile_id ON expenses.expense (profile_id);
CREATE INDEX idx_expense_mission_id ON expenses.expense (mission_id);
CREATE INDEX idx_expense_billable ON expenses.expense (billable);
CREATE INDEX idx_absence_profile_id ON absences.absence (profile_id);
CREATE INDEX idx_invoice_project_id ON billing.invoice (project_id);
CREATE INDEX idx_invoice_line_invoice_id ON billing.invoice_line (invoice_id);
