ALTER TABLE crm.company
    ADD COLUMN IF NOT EXISTS relation_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS company_status VARCHAR(30),
    ADD COLUMN IF NOT EXISTS sector VARCHAR(100),
    ADD COLUMN IF NOT EXISTS manager_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS agency VARCHAR(100),
    ADD COLUMN IF NOT EXISTS current_action VARCHAR(150),
    ADD COLUMN IF NOT EXISTS action_date DATE;
