CREATE TABLE crm.action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    contact_id BIGINT,
    action_type VARCHAR(20) NOT NULL,
    subject VARCHAR(150) NOT NULL,
    comment VARCHAR(4000),
    due_date DATE,
    action_status VARCHAR(20) NOT NULL,
    responsible_name VARCHAR(150),
    next_step VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_action_company FOREIGN KEY (company_id) REFERENCES crm.company (id),
    CONSTRAINT fk_action_contact FOREIGN KEY (contact_id) REFERENCES crm.contact (id)
);

CREATE INDEX idx_action_company_id ON crm.action (company_id);
CREATE INDEX idx_action_contact_id ON crm.action (contact_id);
CREATE INDEX idx_action_status ON crm.action (action_status);
CREATE INDEX idx_action_type ON crm.action (action_type);
