CREATE TABLE timesheets.timesheet (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 profile_id BIGINT NOT NULL, year_number INTEGER NOT NULL, month_number INTEGER NOT NULL,
 status VARCHAR(20) NOT NULL, submitted_at TIMESTAMP WITH TIME ZONE, validated_at TIMESTAMP WITH TIME ZONE,
 validated_by BIGINT, rejected_at TIMESTAMP WITH TIME ZONE, rejected_by BIGINT, rejection_reason VARCHAR(2000),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT fk_timesheet_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile(id),
 CONSTRAINT uk_timesheet_profile_period UNIQUE(profile_id, year_number, month_number),
 CONSTRAINT ck_timesheet_month CHECK (month_number BETWEEN 1 AND 12)
);
ALTER TABLE timesheets.time_entry ADD COLUMN timesheet_id BIGINT;
ALTER TABLE timesheets.time_entry ADD CONSTRAINT fk_time_entry_timesheet FOREIGN KEY (timesheet_id) REFERENCES timesheets.timesheet(id);
CREATE INDEX ix_timesheet_profile_period ON timesheets.timesheet(profile_id, year_number, month_number);
