CREATE TABLE expenses.expense_report (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 profile_id BIGINT NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 year_number INTEGER NOT NULL,
 month_number INTEGER NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
 submitted_at TIMESTAMP WITH TIME ZONE,
 validated_at TIMESTAMP WITH TIME ZONE,
 validated_by BIGINT,
 rejected_at TIMESTAMP WITH TIME ZONE,
 rejected_by BIGINT,
 rejection_reason VARCHAR(2000),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT fk_expense_report_profile FOREIGN KEY (profile_id) REFERENCES staffing.profile(id),
 CONSTRAINT uk_expense_report_profile_period UNIQUE(profile_id, year_number, month_number),
 CONSTRAINT ck_expense_report_month CHECK (month_number BETWEEN 1 AND 12),
 CONSTRAINT ck_expense_report_year CHECK (year_number >= 2000),
 CONSTRAINT ck_expense_report_status CHECK (status IN ('DRAFT','SUBMITTED','VALIDATED','REJECTED'))
);
INSERT INTO expenses.expense_report(profile_id,year_number,month_number,status,created_at,updated_at)
SELECT DISTINCT profile_id, EXTRACT(YEAR FROM expense_date)::INTEGER, EXTRACT(MONTH FROM expense_date)::INTEGER, 'DRAFT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM expenses.expense
ON CONFLICT (profile_id,year_number,month_number) DO NOTHING;
ALTER TABLE expenses.expense ADD COLUMN expense_report_id BIGINT;
UPDATE expenses.expense e SET expense_report_id=r.id FROM expenses.expense_report r WHERE r.profile_id=e.profile_id AND r.year_number=EXTRACT(YEAR FROM e.expense_date)::INTEGER AND r.month_number=EXTRACT(MONTH FROM e.expense_date)::INTEGER;
ALTER TABLE expenses.expense ADD CONSTRAINT fk_expense_report FOREIGN KEY (expense_report_id) REFERENCES expenses.expense_report(id);
ALTER TABLE expenses.expense ALTER COLUMN expense_report_id SET NOT NULL;
CREATE INDEX ix_expense_report_profile_period ON expenses.expense_report(profile_id,year_number,month_number);
CREATE INDEX ix_expense_expense_report ON expenses.expense(expense_report_id);
